[package]
name = "silm"
authors = ["Husayn Haras <husayn@dnmx.org>"]
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3.26"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
